
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const FETCH_CLASSROOMS_SUCCESS = 'FETCH_CLASSROOMS_SUCCESS';
export const FETCH_CLASSROOMS_FAILURE = 'FETCH_CLASSROOMS_FAILURE';